M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu22.04.1} date Tue 15 Nov 2022 03:38:10 PM MST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-15T15:38:10-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X6.37Y18.415
X6.37Y6.985
T0
M30
